@startuml

class FileReader {
    +onload(): void
    +readAsDataURL(files: object[]): void
}

class Image {
    +src: string
    +onload(): void
    +width: number
    +height: number
}

class Canvas {
    +width: number
    +height: number
    +getContext(type: string): object
    +drawImage(image: object, x: number, y: number, width?: number, height?: number): void
    +toDataURL(type?: string, quality?: number): string
}

class tmImage {
    +load(modelURL: string, metadataURL: string): Promise<object>
    +predict(imageElement: object): Promise<object[]>
}

class HTMLDocument {
    +getElementById(id: string): object
}

class HTMLImageElement {
    +src: string
}

class HTMLElement {
    +innerHTML: string
}

class Object {
    +parse(jsonString: string): object
}

class Array {
    +length: number
}

FileReader --> tmImage
Canvas --> tmImage
HTMLDocument --> tmImage
HTMLImageElement --> tmImage
HTMLElement --> tmImage
Array --> tmImage

HTMLDocument --> FileReader
Image --> FileReader
Canvas --> FileReader
HTMLImageElement --> FileReader
HTMLElement --> FileReader
Array --> FileReader

Canvas --> HTMLDocument
HTMLImageElement --> HTMLDocument
HTMLElement --> HTMLDocument

HTMLElement --> Canvas
HTMLImageElement --> Canvas

HTMLImageElement --> HTMLElement

@enduml
